# Generated by Django 5.2.10 on 2026-01-21 22:38

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('contact_person', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=60)),
                ('status', models.CharField(choices=[('isActive', 'Active'), ('isNotActive', 'Not Active')], default='isActive')),
                ('total_vol', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('driver', 'Driver')], default='driver', max_length=10)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('license_no', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=60)),
                ('trips', models.PositiveBigIntegerField(default=0)),
                ('leave_date', models.DateTimeField(blank=True, null=True)),
                ('return_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('onLeave', 'On Leave'), ('isAvailable', 'Available'), ('onDuty', 'On Duty')], default='isAvailable')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('truck_no', models.CharField(max_length=10, unique=True)),
                ('type', models.CharField(max_length=20)),
                ('last_maintenance', models.DateTimeField()),
                ('next_due', models.DateTimeField()),
                ('status', models.CharField(choices=[('onMaintenance', 'Maintenance'), ('isGood', 'Good Condition')], default='isGood')),
                ('driver', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='logistics.driver')),
            ],
        ),
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('startingpoint', models.CharField(default='Nairobi', max_length=100)),
                ('destination', models.CharField(default='Nairobi', max_length=100)),
                ('status', models.CharField(choices=[('cancelled', 'Cancelled'), ('inprogress', 'InProgress'), ('shipping', 'Shipping'), ('delivered', 'Delivered')])),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistics.driver')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistics.party')),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistics.truck')),
            ],
        ),
    ]
