# Generated by Django 5.2.10 on 2026-01-21 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0003_alter_truck_driver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journey',
            name='driver',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistics.driver'),
        ),
    ]
