# Generated by Django 5.2.10 on 2026-01-21 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0004_alter_journey_driver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journey',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistics.driver'),
        ),
        migrations.AlterField(
            model_name='journey',
            name='truck',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistics.truck'),
        ),
    ]
