# Generated by Django 5.2.10 on 2026-01-26 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0005_alter_journey_driver_alter_journey_truck'),
    ]

    operations = [
        migrations.AddField(
            model_name='journey',
            name='cost',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='journey',
            name='description',
            field=models.TextField(default='goods'),
        ),
    ]
