# Generated by Django 5.2.10 on 2026-01-27 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0006_journey_cost_journey_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truck',
            name='last_maintenance',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='truck',
            name='next_due',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
