# Generated by Django 5.2.10 on 2026-01-30 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0007_alter_truck_last_maintenance_alter_truck_next_due'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='trips',
            new_name='complete_trips',
        ),
        migrations.AddField(
            model_name='driver',
            name='incomplete_trips',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
