# Generated by Django 5.2.10 on 2026-01-31 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0008_rename_trips_driver_complete_trips_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
