# Generated by Django 5.2.10 on 2026-01-31 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0009_party_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journey',
            name='cost',
        ),
        migrations.AddField(
            model_name='journey',
            name='weight',
            field=models.IntegerField(default=0),
        ),
    ]
