# Generated by Django 5.2.10 on 2026-02-02 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0010_remove_journey_cost_journey_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='pricepaid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='party',
            name='voltransported',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='party',
            name='total_vol',
            field=models.IntegerField(default=0),
        ),
    ]
