# Generated by Django 5.2.10 on 2026-02-11 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0011_party_pricepaid_party_voltransported_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journey',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
