# Generated by Django 5.2.10 on 2026-02-11 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0012_journey_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journey',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
