# Generated by Django 5.2.10 on 2026-02-11 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0013_alter_journey_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='phone',
            field=models.CharField(max_length=30),
        ),
    ]
